### PR TITLE
Update self-merge-rates.md

### PR DESCRIPTION
**Pull request by ElizabethN**
Corrects links to the images and moves them into the Visualization section. Also adds context to images.

Signed-off-by: Elizabeth Barron <elizabeth@naramore.net>

### CODE REVIEW

**Comment by ElizabethN** [comment]
@germonprez adding you as a reviewer only to avoid the irony of me self-merging this. :joy:

cc @rpaik - just made a few tweaks to look a little nicer on the website. :blush:

**Review by germonprez — APPROVED** [review]
I approve for reasons of not self merging.

**Comment by germonprez** [comment]
Approved!

**Comment by ElizabethN** [comment]
Grrr, and I found a typo!

**Comment by germonprez** [comment]
You have to self merge at this point.

**Pull request merged**
