### PR TITLE
Language Distribution Metric Draft

### PR DESCRIPTION
**Pull request by sgoggins**

### CODE REVIEW

**Review by GeorgLink — CHANGES_REQUESTED** [review]
Could you please link to the metric from the focus area's README?

**Comment by germonprez** [comment]
@klumb taking a look at getting this across the finish line.

**Comment by ritik-malik** [comment]
Hi @klumb , since `what` focus-area has been renamed to `contributions`, this metric should be moved to `contributions` directory.
Right now it created a new redundant `what` directory.

**Comment by ritik-malik** [comment]
Can I fix this?
We also need to add this new metric to the README

**Comment by klumb** [comment]
@ritik-malik thanks for paying attention. I was already in the process of submitting a PR for that. Feel free to review it. PR #133

**Pull request merged**
