### PR TITLE
fixed redirection of metric.md

### PR DESCRIPTION
**Pull request by ritik-malik**
Changed the metric file name to lower-case and with hyphen instead of underscore because :
1. The redirection from README.md was giving a 404
2. All other metrics are in lower-case, the [unofficial guide](https://docs.google.com/document/d/1chPzgJa49sO_f3wVqp_NLJupSVyKHSVyuFuwzl4m4KI/edit?pli=1#heading=h.4ejkic2mb7z1) also says the same

Signed-off-by: ritik-malik <ritik18406@iiitd.ac.in>

### CODE REVIEW

**Comment by GeorgLink** [comment]
Thanks @ritik-malik 

Merging is blocked by website, which needs to be updated: https://chaoss.community/metric-review-cycle-duration-within-a-change-request/

@klumb can you please merge this and update the website?

**Review by GeorgLink — APPROVED** [review]
Thanks @ritik-malik

Merging is blocked by website, which needs to be updated: https://chaoss.community/metric-review-cycle-duration-within-a-change-request/

@klumb can you please merge this and update the website?

**Comment by klumb** [comment]
done and done

thank you @ritik-malik

**Comment by GeorgLink** [comment]
Awesome, thanks @klumb

**Pull request merged**
