### PR TITLE
Clarify metric "Change Request Closure Ratio"

### PR DESCRIPTION
**Pull request by canasdiaz**
Previous definition of the metric was not clear, as it could be understand that it is measuring something similar to BMI or REI metrics. Changes try to shed more light on the specific added value of the metric and remove a reference to the REI metric, which is calculated following a different approach.

### CODE REVIEW

**Comment by geekygirldawn** [comment]
I actually think that what you proposed might be better as a different metric. We had the discussion several times (probably both in the common WG and the metrics model WG) about whether this metric should be comparing new requests in a time period with the closed requests in that same time period, and we made the decision to compare total number of requests during a time period with closed requests in that time period.

The rationale is that I'm trying to measure whether a project can keep up with requests over time, not just new ones, but also accumulated ones that might be creating a backlog of requests if they don't keep up with them. Because what you measure drives behavior, I use this metric to encourage maintainers to close without merge things that aren't likely to ever be merged or things that have become too outdate to be practical to merge. While also encouraging them to merge the good pull requests without letting them sit around for too long. If I just measured newly created requests, it might encourage people to neglect / ignore those earlier requests.

With that said, this keeps coming up, which makes me think that it might be worth creating a second metric as you've defined it and making sure that both metrics link to each other so that people can find the one they want to measure, since there is clearly an interest in measuring this both ways. 

We should probably discuss this in the common WG meeting this week.

**Comment by canasdiaz** [comment]
> We had the discussion several times (probably both in the common WG and the metrics model WG) about whether this metric should be comparing new requests in a time period with the closed requests in that same time period, and we made the decision to compare total number of requests during a time period with closed requests in that time period.

@geekygirldawn happy to discuss metrics (always!) :nerd_face: 

Just in case, I think there is a misunderstanding here. The changes I submitted are not trying to change the metric you defined; my aim was to clarify it. It seems I did not succeed ;) 

If we calculate the current metric monthly, my understanding is that for each month, we use these two variables:
 - PRs submitted during the month M1
 - PRs submitted and closed during the month M1
 
There is a different metric, which is the REI. If we calculate REI monthly, we use these two variables:
 - PRs submitted during the month M1
 - PRs closed during the month M1
 
To make visible the difference in the second variable, I introduced the word "**new**". For REI you measure just closed requests, no matter if they are one day or one year old.

**Comment by geekygirldawn** [comment]
If we calculate the Change request closure ratio metric monthly, for each month, we use these two variables:
- Total open PRs: PRs submitted during the month M1 + PRs that were already open at the beginning of M1 from previous months
- PRs closed during the month M1

Both of the definitions you have above are good things to measure, but neither of them are actually how we measure this metric. This has been confusing for people, which is why I wonder if we need an additional metric to define what you described in your first scenario. We also need to define REI, but we have an issue already for that one :)

**Comment by canasdiaz** [comment]
@geekygirldawn Mistery solved then.

Regarding the two metrics I included above. I don't see a use case for the first one, as it excludes everything that happens before each of the series.

To clarify the metric you submitted, I will try to add more information (extracted from your comments above) so our folks don't have the same issues I had understanding this metric. Do you think it makes sense?

**Comment by geekygirldawn** [comment]
> To clarify the metric you submitted, I will try to add more information (extracted from your comments above) so our folks don't have the same issues I had understanding this metric. Do you think it makes sense?

That would be great! Several people have been confused by the way it's worded now, so I'd love your help in improving it!

**Comment by ElizabethN** [comment]
We discussed this in the Common working group today and decided to close this without Merge, as this was a separate metric. Happy to take a look at any new metrics that come as a result of this PR's discussion.

**Comment by canasdiaz** [comment]
Thanks for the explanation @ElizabethN . I appreciate it.

**Pull request closed without merging**
